# Generated by Django 3.2.8 on 2021-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
