# Generated by Django 3.2.8 on 2021-12-17 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Mesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Silla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mesa.mesa')),
            ],
        ),
    ]
